### ISSUE TITLE
Idea: Have multiple ACs per configuraion

### ISSUE THREAD

**Issue by GuyKh** [yonatanp/electrasmart-custom-component#1]
I have 4 ACs at home,
Using the same imei and token.
but multiple ACs

```
climate:
  - platform: electrasmart
    imei: "2b9500000..."
    token: "1fd4a2e86..."
    acs: 
        - ac_id: 12345
           name: MyLivingRoomAC
        - 23456
           name: BedroomAC
```
